server:
  port: 9091

spring:
  application:
    name: File-Upload

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:fileupload_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Pgsql#321}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true