server:
  port: 9091

spring:
  application:
    name: File-Upload

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:fileupload_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Pgsql#321}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    root: INFO
    com.spring upload: DEBUG    # your base package
  file:
    name: logs/app.log
  pattern:
    console: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"


